Repository raytracers/miniRT, pull requests merged in 2023-03, with the labels that each got.

#16 15 create the datatypes for interpreting the scene
  headers/types.h
Labels: enhancement

#26 25 add is double str function to libft
  Makefile
  UnitTests/CMakeLists.txt
  UnitTests/LibftTests/CMakeLists.txt
  UnitTests/LibftTests/IsDoubleStrTests.cpp
  libft/Makefile
  libft/ft_isdouble_str.c
  libft/libft.h
Labels: enhancement

#34 33 is normalized function
  Makefile
  UnitTests/CMakeLists.txt
  UnitTests/SceneTests/CMakeLists.txt
  UnitTests/SceneTests/IsNormalized.cpp
  headers/input.h
  headers/mini_rt.h
  headers/types.h
  sources/input/is_normalized.c
Labels: enhancement

#40 35 initialize t camera structure
  Makefile
  UnitTests/CMakeLists.txt
  UnitTests/SceneTests/CMakeLists.txt
  UnitTests/SceneTests/InitCamera.cpp
  headers/input.h
  sources/input/init_camera.c
Labels: enhancement

#41 37 init cylinder
  UnitTests/CMakeLists.txt
  UnitTests/SceneTests/CMakeLists.txt
  UnitTests/SceneTests/InitCylinder.cpp
  headers/input.h
  sources/input/init_cylinder.c
Labels: enhancement

#42 29 add operations to the t elist linked list
  Makefile
  UnitTests/CMakeLists.txt
  UnitTests/ElistTests/CMakeLists.txt
  UnitTests/ElistTests/ElistAddback.cpp
  UnitTests/ElistTests/ElistNew.cpp
  headers/input.h
  headers/types.h
  sources/types/init_camera.c
  sources/types/init_cylinder.c
  sources/types/init_sphere.c
  sources/types/t_elist.c
Labels: enhancement

#43 38 init plane
  Makefile
  UnitTests/CMakeLists.txt
  UnitTests/SceneTests/CMakeLists.txt
  UnitTests/SceneTests/InitPlane.cpp
  headers/input.h
  headers/types.h
  sources/types/init_plane.c
Labels: documentation, enhancement

#47 46 reorganize types
  UnitTests/ElistTests/ElistAddback.cpp
  UnitTests/ElistTests/ElistNew.cpp
  UnitTests/SceneTests/InitCamera.cpp
  UnitTests/SceneTests/InitCylinder.cpp
  UnitTests/SceneTests/InitPlane.cpp
  UnitTests/SceneTests/InitSphere.cpp
  headers/types.h
  sources/types/init_camera.c
  sources/types/init_cylinder.c
  sources/types/init_plane.c
  sources/types/init_sphere.c
  sources/types/t_elist.c
Labels: enhancement, Refactor

#50 49 new members for t camera and t window
  UnitTests/SceneTests/InitCamera.cpp
  headers/types.h
  sources/mlx/initialization.c
  sources/types/init_camera.c
Labels: enhancement

#54 Feat: Created Intersect type
  headers/types.h
Labels: enhancement

#56 45 init light
  UnitTests/CMakeLists.txt
  UnitTests/SceneTests/CMakeLists.txt
  UnitTests/SceneTests/InitLight.cpp
  headers/types.h
  sources/types/init_light.c
Labels: documentation, enhancement

#55 44 init ambient light
  UnitTests/CMakeLists.txt
  UnitTests/SceneTests/CMakeLists.txt
  UnitTests/SceneTests/InitAmbientLight.cpp
  headers/types.h
  sources/types/init_ambient_light.c
Labels: documentation

#63 refactor: clean up code, norminette fixing, use assertions in tests
  UnitTests/SceneTests/SceneLoader.cpp
  headers/app.h
  headers/error.h
  sources/app/destroy_scene.c
  sources/input/arg_validator.c
  sources/input/error.c
  sources/input/get_point.c
  sources/input/scene_loader.c
  sources/input/scene_open.c
  sources/mlx/initialization.c
  sources/render/sphere_intersection.c
  sources/types/init_camera.c
  sources/types/init_cylinder.c
  sources/types/init_sphere.c
Labels: Refactor

#67 66 small fixes
  UnitTests/IntersectionTests/SphereIntersection.cpp
  UnitTests/MathTests/RotationMatrix.cpp
  UnitTests/MathTests/ViewTransformMatrix.cpp
  headers/types.h
  sources/operations/rtm.c
  sources/operations/vtm.c
  sources/render/sphere_intersection.c
  sources/types/init_cylinder.c
  sources/types/init_plane.c
Labels: bug

#72 71 add ambient light
  scenes/circle.rt
  sources/mlx/initialization.c
  sources/render/get_px_color.c
Labels: enhancement

#75 Feat: check_scene implementation and addition to main control flow
  Makefile
  UnitTests/CMakeLists.txt
  UnitTests/SceneTests/CMakeLists.txt
  UnitTests/SceneTests/SceneChecker.cpp
  headers/input.h
  libft/Makefile
  libft/get_next_line.c
  libft/get_next_line_utils.c
  libft/libft.h
  scenes/tests/no_camera.rt
  scenes/tests/no_light.rt
  scenes/tests/nolight_nocamera.rt
  sources/input/scene_checker.c
  sources/input/scene_loader.c
  sources/input/scene_open.c
  sources/main.c
Labels: bug, enhancement

#77 76 add color to light
  UnitTests/SceneTests/InitLight.cpp
  headers/types.h
  sources/render/get_px_color.c
  sources/types/init_light.c
Labels: enhancement

#79 78 interactive mode
  Makefile
  headers/mlx_functions.h
  headers/operations.h
  headers/render.h
  headers/types.h
  sources/main.c
  sources/mlx/events.c
  sources/mlx/initialization.c
  sources/operations/matrix.c
  sources/operations/transform_vector.c
  sources/render/interactive_render.c
  sources/render/interactive_z_axis.c
  sources/render/move_scene.c
  sources/render/rotate_scene.c
  sources/render/transform_scene.c
Labels: enhancement

#81 80 add menu
  headers/types.h
  images/Interactive_menu.xpm
  images/Render_menu.xpm
  sources/render/get_px_color.c
  sources/render/interactive_render.c
  sources/render/render_scene.c
Labels: enhancement

#83 73 plane intersection
  Makefile
  UnitTests/CMakeLists.txt
  UnitTests/IntersectionTests/CMakeLists.txt
  UnitTests/IntersectionTests/PlaneIntersection.cpp
  headers/operations.h
  headers/render.h
  scenes/plane.rt
  scenes/plane2.rt
  sources/operations/vector_operations2.c
  sources/render/get_intersection.c
  sources/render/plane_intersection.c
Labels: enhancement
