Repository raytracers/miniRT, pull requests merged in 2023-04, with the labels that each got.

#84 82 specular lihgting
  Makefile
  headers/render.h
  sources/render/compute_ambient.c
  sources/render/compute_diffuse.c
  sources/render/compute_specular.c
  sources/render/get_px_color.c
  sources/render/render_scene.c
Labels: enhancement, Refactor

#86 85 define keys to header
  Makefile
  headers/mini_rt.h
  headers/mlx_keys.h
Labels: enhancement, Refactor

#88 Fix: intersection when camera is inside shere now behaves correctly
  UnitTests/IntersectionTests/SphereIntersection.cpp
  UnitTests/MathTests/QuadraticSolver.cpp
  headers/operations.h
  scenes/inside_circle.rt
  sources/operations/quadratic_solver.c
  sources/render/sphere_intersection.c
Labels: bug

#89 Feat: Cylinder intersection
  Makefile
  UnitTests/CMakeLists.txt
  UnitTests/IntersectionTests/CMakeLists.txt
  UnitTests/IntersectionTests/CylinderIntersection.cpp
  UnitTests/SceneTests/SceneChecker.cpp
  headers/operations.h
  headers/render.h
  scenes/common_core.rt
  scenes/cylinder.rt
  scenes/cylinder2.rt
  scenes/cylinder3.rt
  sources/input/is_normalized.c
  sources/mlx/events.c
  sources/operations/cylinder_quadratic.c
  sources/operations/quadratic_solver.c
  sources/render/cylinder_intersection.c
  sources/render/get_intersection.c
  sources/render/plane_intersection.c
  sources/render/sphere_intersection.c
  sources/types/init_cylinder.c
Labels: enhancement

#90 Cone intersection
  Makefile
  headers/operations.h
  headers/render.h
  headers/types.h
  scenes/cone.rt
  sources/input/get_element.c
  sources/mlx/events.c
  sources/operations/cone_quadratic.c
  sources/operations/quadratic_solver.c
  sources/render/cone_intersection.c
  sources/render/get_intersection.c
  sources/render/sphere_intersection.c
  sources/render/transform_scene.c
  sources/types/t_elist.c
Labels: enhancement

#92 91 bug fixing
  Makefile
  headers/mlx.h
  sources/mlx/events.c
  sources/render/interactive_render.c
  sources/render/render_scene.c
  sources/types/init_camera.c
Labels: bug

#96 Fix: Render image now persists even if the windows is minimized
  Makefile
  headers/render.h
  headers/types.h
  sources/mlx/initialization.c
  sources/render/interactive_render.c
  sources/render/render_loop.c
  sources/render/render_scene.c
Labels: bug

#101 fix: now specular light computation takes brightness into account
  sources/render/compute_specular.c
Labels: bug

#99 98 new scenes
  scenes/amongus.rt
  scenes/android.rt
  scenes/cage.rt
  scenes/common_core.rt
  scenes/cool_spheres.rt
  scenes/cylinder.rt
  scenes/inside_circle.rt
  scenes/multiple_cones.rt
  scenes/plane2.rt
  scenes/pokeball.rt
  scenes/simple_scene1.rt
  scenes/simple_scene2.rt
  scenes/simple_scene3.rt
  scenes/simple_spheres.rt
  scenes/solar_system.rt
  scenes/spheres.rt
  scenes/subject.rt
Labels: enhancement

#104 103 create readme
  README.md
Labels: documentation
